### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by BreeBreeXD** [vk-brain/sketal#112]
### Ожидаемый результат (что должно было произойти, чего вы ожидали)
Запуск бота
### Фактический результат (что произошло на самом деле, что не должно было произойти или должно было произойти иначе)
Ошибка 
C:\Users\BreeBree\Desktop\sketal-master>python bot.py
Traceback (most recent call last):
  File "bot.py", line 387, in <module>
    from settings_real import BotSettings
ModuleNotFoundError: No module named 'settings_real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 390, in <module>
    from settings import BotSettings
  File "C:\Users\BreeBree\Desktop\sketal-master\settings.py", line 18, in <module>
    from plugins import *
  File "C:\Users\BreeBree\Desktop\sketal-master\plugins\__init__.py", line 38, in <module>
    import_plugins(__name__)
  File "C:\Users\BreeBree\Desktop\sketal-master\plugins\__init__.py", line 36, in import_plugins
    import_plugins(full_name)
  File "C:\Users\BreeBree\Desktop\sketal-master\plugins\__init__.py", line 20, in import_plugins
    module = importlib.import_module(full_name)
  File "C:\Program Files (x86)\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\BreeBree\Desktop\sketal-master\plugins\games\dueler.py", line 4, in <module>
    import peewee_async, peewee, asyncio, random, time
  File "C:\Program Files (x86)\lib\site-packages\peewee_async.py", line 28, in <module>
    import aiopg
  File "C:\Program Files (x86)\lib\site-packages\aiopg\__init__.py", line 5, in <module>
    from .connection import connect, Connection, TIMEOUT as DEFAULT_TIMEOUT
  File "C:\Program Files (x86)\lib\site-packages\aiopg\connection.py", line 109
    self._conn = psycopg2.connect(dsn, async=True, **kwargs)
                                           ^
SyntaxError: invalid syntax
### Дополнительная информация (лог ошибок, какие настройки использовались, какую версию python используете)
Устанавливал по инструкции, питон последний с сайта, запускал консоль под администратором

**Comment by DexLM01** [comment]
Скорее всего у вас не 3.6 версия python

**Comment by BreeBreeXD** [comment]
@DexLM01 у меня 3.7, пробовать ставить ниже?
