### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by Kirillxd911** [vk-brain/sketal#114]
Пожалуйста, не забудьте внимательно прочитать README.md и всё настроить точно как в инструкциях. Попробуйте ещё раз проверить введённые данные, подождите немного. Убедитесь, что у вас есть доступ к интернету, vk.com.

#### Что случилось? В чём ошибка?
Опишите вашу проблему, расскажите максимально подробно, что произошло и почему. Расскажите, что вы хотели, что сделали.
Пишу "python3.6 run.py" и вроде бы, кажется, что все нормально, у бот появляется доступ к аккаунту и группе, но в конце концов он не отвечает.

#### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
Что нужно запустить? Как нужно запустить? Где нужно запустить?
Запустить run.py из папки с ботом.

[18.08.19 03:17:14] INFO    : Initializing bot
[18.08.19 03:17:14] INFO    : Initializing vk clients
[18.08.19 03:17:14] INFO    : Logged in as: AAAAAAAAAAAAAAA (BBBBBBBBBBBB)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 44-49: ordinal not in range(128)
Call stack:
  File "run.py", line 14, in <module>
    bot = bot.Bot(BotSettings)
  File "/var/www/sketal/bot.py", line 41, in __init__
    self.api = VkController(settings, logger=self.logger, loop=self.loop)
  File "/var/www/sketal/utils/plus.py", line 55, in __init__
    loop.run_until_complete(self.init_vk())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/var/www/sketal/utils/plus.py", line 84, in init_vk
    await client.user_with_token(user[1])
  File "/var/www/sketal/utils/api.py", line 182, in user_with_token
    self.logger.info(f"Logged in as: {self_data['first_name']} {self_data['last_name']} "
Message: 'Logged in as: CCCCCCCCC (DDDDDDDDD)'
Arguments: ()
[18.08.19 03:17:14] INFO    : Logged in as: EEEEEEEEEEE (FFFFFFFFFFF)
[18.08.19 03:17:14] INFO    : Loading plugins
[18.08.19 03:17:14] WARNING : No key specified for Yandex Speechkit Cloud. Google will be used. You can get your key - https://tech.yandex.ru/speechkit/cloud/.
[18.08.19 03:17:14] INFO    : Bot successfully initialized
[18.08.19 03:17:14] INFO    : Started to process messages
5
[18.08.19 03:18:02] INFO    : Attempting to turn bot off
[18.08.19 03:18:02] INFO    : Stopped to process messages
_______________________
После Started to process messages консоль просто не отвечает и можно в нее писать все что угодно, но спустя время она сообщает что бот остановил обработку сообщений.
В группу с ботом пишу боту, но он не отвечает.

**Comment by Yardanico** [comment]
"UnicodeEncodeError: 'ascii' codec can't encode characters in position 44-49: ordinal not in range(128)
Call stack:"
Попробуйте поставить en_US.UTF-8 или ru_RU.UTF-8 локаль
