### ISSUE TITLE
бот отказывается запукаться

### ISSUE THREAD

**Issue by Andrew1090** [vk-brain/sketal#119]
Пожалуйста, не забудьте внимательно прочитать README.md и всё настроить точно как в инструкциях. Попробуйте ещё раз проверить введённые данные, подождите немного. Убедитесь, что у вас есть доступ к интернету, vk.com.

#### Что случилось? В чём ошибка?
запускаю бота, а он вылетает с одной и той же ошибкой пробовал на python3.6-3.7 причем все делал по инструкции.
File "C:\Users\Андрей\Desktop\sketal-master\run.py", line 9, in <module>
    from settings_prod import BotSettings
ModuleNotFoundError: No module named 'settings_prod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Андрей\Desktop\sketal-master\settings.py", line 5, in <module>
    class BotSettings(BaseSettings):
  File "C:\Users\Андрей\Desktop\sketal-master\settings.py", line 33, in BotSettings
    QuoteDoerPlugin(),
  File "C:\Users\Андрей\Desktop\sketal-master\plugins\content\content_quote_doer\quote.py", line 24, in __init__
    self.f = ImageFont.truetype(self.get_path("font.ttf"), 24)
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\ImageFont.py", line 259, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\ImageFont.py", line 143, in __init__
    self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
OSError: cannot open resource
#### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
как повторить не знаю

**Comment by Andrew1090** [comment]
простите за беспокойство уже разобрался, проблема была в пути(кирилица)

**Comment by Andrew1090** [comment]
ок теперь другая проблема 
![bandicam 2018-09-21 16-22-36-878](https://user-images.githubusercontent.com/38564286/45872353-0299ca00-bdba-11e8-952b-2d23430ea770.jpg)
почему он не обрабатывает сообщения?
