### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Noneeer** [vk-brain/sketal#81]
### Фактический результат (что произошло на самом деле, что не должно было произойти или должно было произойти иначе)

```
Traceback (most recent call last):
  File "bot.py", line 397, in <module>
    bot.longpoll_run()
  File "bot.py", line 255, in longpoll_run
    self.loop.run_until_complete(self.main_task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 466, in run_u
ntil_complete
    return future.result()
  File "bot.py", line 212, in longpoll_processor
    self.values['ts'] = events['ts']
KeyError: 'ts'
```

### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
Само собой, через некоторое время работы

### Дополнительная информация (лог ошибок, какие настройки использовались, какую версию python используете)
python 3.6

**Comment by SevastyanDark** [comment]
Попробуй обнови зависимости

**Comment by SevastyanDark** [comment]
Ошибка возникает когда бот простаивает или кто-то пишет?

**Comment by Noneeer** [comment]
@SevastyanDark Когда простаивает (вроде)

**Comment by SevastyanDark** [comment]
Это на heroku?
Вплолне возможно завис сервер ВК

**Comment by Noneeer** [comment]
@SevastyanDark Нет, это на моем сервере, еще я запускал у себя на компьютере было тоже самое.

**Comment by SevastyanDark** [comment]
Попробуй запускать 
'''
python bot_runner.py
'''

**Comment by SevastyanDark** [comment]
И да, с инетом все ок?

**Comment by Noneeer** [comment]
@SevastyanDark С инетом все просто идеально, не может же он 10 раз подряд пропасть.
Через bot_runner тоже самое.

**Comment by SevastyanDark** [comment]
Ок, завтра сделаю PR

**Comment by SevastyanDark** [comment]
Будет ещё плагин

**Comment by SevastyanDark** [comment]
И фикс этого

**Comment by SevastyanDark** [comment]
Попробуй с этими изменениями

**Comment by Noneeer** [comment]
@SevastyanDark Сделал все как ты сказал, тоже самое, только ошибка другая

```
Traceback (most recent call last):
  File "bot.py", line 400, in <module>
    bot.longpoll_run()
  File "bot.py", line 258, in longpoll_run
    self.loop.run_until_complete(self.main_task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "bot.py", line 216, in longpoll_processor
    for event in events['updates']:
KeyError: 'updates'
```

**Comment by michaelkrukov** [comment]
Проблема в том, что от вк пришёл пустой запрос или что-то такое. Надо узнать, что пришло и почему пустое.

**Comment by Noneeer** [comment]
@SevastyanDark  @michaelkrukov В немного старой версии кстати такой ошибки не возникает.

**Comment by SevastyanDark** [comment]
@michaelkrukov @Noneeer Скорее всего ВК вернул ошибку 2
```
"failed":2 — истекло время действия ключа, нужно заново получить key методом messages.getLongPollServer.
```

**Comment by michaelkrukov** [comment]
@SevastyanDark Это и есть обработка ответов от ВК с ошибками 1-3 https://github.com/vk-brain/sketal/blob/master/bot.py#L199
