### ISSUE TITLE
(Другая ошибка)

### ISSUE THREAD

**Issue by arseny2606** [vk-brain/sketal#88]
### Ожидаемый результат (что должно было произойти, чего вы ожидали)
Запуск бота
### Фактический результат (что произошло на самом деле, что не должно было произойти или должно было произойти иначе)
Ошибка
### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
python bot.py
### Дополнительная информация (лог ошибок, какие настройки использовались, какую версию python используете)
python 3.6.4, bot.py    ```
 [18.03.08 18:25:29] INFO    : Initializing bot
bot.py     [18.03.08 18:25:29] INFO    : Initializing vk clients
Traceback (most recent call last):
  File "bot.py", line 397, in <module>
    bot = Bot(BotSettings)
  File "bot.py", line 42, in __init__
    self.api = VkController(settings, logger=self.logger)
  File "C:\Users\user\Desktop\sketal-master\vk\plus.py", line 43, in __init__
    raise ValueError("You have wrong entity in `USERS` in settings: " + str(PACK
))
ValueError: You have wrong entity in `USERS` in settings: ('USER', '423a469e9877
8c2cb7ea5fd0fb6da624625d9d273c5d3dda5c2c1c2587b0ba47cfc29fe012f167a0e0b4d')

C:\Users\user\Desktop\sketal-master>python bot.py
bot.py     [18.03.08 18:26:21] INFO    : Initializing bot
bot.py     [18.03.08 18:26:21] INFO    : Initializing vk clients
auth.py    [18.03.08 18:26:22] ERROR   : Authorization error (incorrect password
)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", lin
e 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", lin
e 814, in __init__
    self.do_handshake()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", lin
e 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", lin
e 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth.vk.com', port=
443): Max retries exceeded with url: /token?grant_type=password&client_id=227400
3&client_secret=hHbZxrka2uZ6jB1inYsH&username=%D0%9B%D0%9E%D0%93%D0%98%D0%9D%20%
D0%9F%D0%9E%D0%9B%D0%AC%D0%97%D0%9E%D0%92%D0%90%D0%A2%D0%95%D0%9B%D0%AF&password
=%D0%9F%D0%90%D0%A0%D0%9E%D0%9B%D0%AC%20%D0%9F%D0%9E%D0%9B%D0%AC%D0%97%D0%9E%D0%
92%D0%90%D0%A2%D0%95%D0%9B%D0%AF (Caused by SSLError(SSLError(1, '[SSL: CERTIFIC
ATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 397, in <module>
    bot = Bot(BotSettings)
  File "bot.py", line 42, in __init__
    self.api = VkController(settings, logger=self.logger)
  File "C:\Users\user\Desktop\sketal-master\vk\plus.py", line 55, in __init__
    loop.run_until_complete(self.init_vk())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base
_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\user\Desktop\sketal-master\vk\plus.py", line 87, in init_vk
    await client.user(user[1], user[2], self.app_id, self.scope)
  File "C:\Users\user\Desktop\sketal-master\vk\api.py", line 209, in user
    self.token = await self.auth.get_token(username, password, app_id, scope)
  File "C:\Users\user\Desktop\sketal-master\vk\auth.py", line 173, in get_token
    return await fallback.get_token(username, password, app_id, scope)
  File "C:\Users\user\Desktop\sketal-master\vk\auth.py", line 18, in get_token
    res = json.loads(requests.get(url.format(username=username, password=passwor
d)).text)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='oauth.vk.com', port=443)
: Max retries exceeded with url: /token?grant_type=password&client_id=2274003&cl
ient_secret=hHbZxrka2uZ6jB1inYsH&username=%D0%9B%D0%9E%D0%93%D0%98%D0%9D%20%D0%9
F%D0%9E%D0%9B%D0%AC%D0%97%D0%9E%D0%92%D0%90%D0%A2%D0%95%D0%9B%D0%AF&password=%D0
%9F%D0%90%D0%A0%D0%9E%D0%9B%D0%AC%20%D0%9F%D0%9E%D0%9B%D0%AC%D0%97%D0%9E%D0%92%D
0%90%D0%A2%D0%95%D0%9B%D0%AF (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_
VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03C78430>
```

**Comment by michaelkrukov** [comment]
Во-первых, ты только что опубликовал свой токен.

**Comment by arseny2606** [comment]
ничего

**Comment by arseny2606** [comment]
мне тот акк не нужен

**Comment by michaelkrukov** [comment]
Во-вторых, я полагаю, надо не USER, а user. Регистр играет роль. Надо быть внимательнее и больше не создавать issues "У меня ошибка, потоум что я не умею читать и делать как в иструкциях.".

**Comment by arseny2606** [comment]
спасибо, заработало вроде
